# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
import_types = ["crate::sqlite_mapping::*"]
custom_type_derives = ["diesel::sql_types::SqlType", "std::fmt::Debug"]

[migrations_directory]
dir = "/Users/ioaths/Documents/Github/poruos/migrations"
